# Generated by Django 4.1.10 on 2025-10-11 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频分类',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='标签')),
                ('file', models.FileField(upload_to='videos/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('video', '视频'), ('image', '图片'), ('model', '模型')], max_length=10, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_extension', models.CharField(max_length=10, verbose_name='文件扩展名')),
                ('md5_hash', models.CharField(max_length=32, unique=True, verbose_name='MD5哈希值')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='时长')),
                ('resolution', models.CharField(blank=True, max_length=20, null=True, verbose_name='分辨率')),
                ('codec', models.CharField(blank=True, max_length=50, null=True, verbose_name='编码格式')),
                ('bitrate', models.IntegerField(blank=True, null=True, verbose_name='比特率')),
                ('frame_rate', models.FloatField(blank=True, null=True, verbose_name='帧率')),
                ('security_level', models.IntegerField(choices=[(1, '公开'), (2, '内部'), (3, '秘密'), (4, '绝密')], default=1, verbose_name='重要级别')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('view_count', models.IntegerField(default=0, verbose_name='观看次数')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='缩略图')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.category', verbose_name='分类')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频评论',
                'verbose_name_plural': '视频评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=20, verbose_name='分辨率')),
                ('bitrate', models.IntegerField(verbose_name='比特率')),
                ('file', models.FileField(upload_to='videos/versions/', verbose_name='版本文件')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='videos.video', verbose_name='原视频')),
            ],
            options={
                'verbose_name': '视频版本',
                'verbose_name_plural': '视频版本',
                'unique_together': {('video', 'resolution', 'bitrate')},
            },
        ),
        migrations.CreateModel(
            name='VideoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频收藏',
                'verbose_name_plural': '视频收藏',
                'unique_together': {('video', 'user')},
            },
        ),
    ]
