# Generated by Django 4.1.10 on 2025-10-14 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_locationtag_permissiongroup_projecttag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('download_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('download_source', models.CharField(default='data_management', max_length=50, verbose_name='下载来源')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('source_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datamodel', verbose_name='来源模型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '下载日志',
                'verbose_name_plural': '下载日志',
            },
        ),
    ]
