# Generated by Django 4.1.10 on 2025-10-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_downloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='source_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.datamodel', verbose_name='来源模型'),
        ),
    ]
